#!/bin/sh

# "/mv who" command comes from the Multiverse-Core plugin and list players across dimensions

. .server-settings

screen -S ${GNUSCREEN_SESSION} -p ${GNUSCREEN_WINDOW} -X stuff "mem"`printf \\\r`
screen -S ${GNUSCREEN_SESSION} -p ${GNUSCREEN_WINDOW} -X stuff "mv who"`printf \\\r`
sleep 1
tail -50 ${SERVER_ROOT}/logs/latest.log | awk '/CONSOLE issued server command:/,lastline' 
